name: testique
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.8
  google_fonts: ^6.1.0
  auto_route: ^7.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  mocktail: ^1.0.2


flutter:
  uses-material-design: true
  assets:
    - assets/images/

# todo(netos23) ios setup
flutter_native_splash:
  color: "#C1464B"
  image: assets/splash/splash.jpeg
  color_dark: "#C1464B"
  image_dark: assets/splash/splash.jpeg
  android_12:
    image: assets/splash/splash.jpeg
    icon_background_color: "#C1464B"
    image_dark: assets/splash/splash.jpeg
    icon_background_color_dark: "#C1464B"